Repository iTwin/appui, pull requests merged in 2023-11, with the labels that each got.

#574 Fix `IModelViewportControl` in case `applicationData` is not provided
  common/changes/@itwin/appui-react/viewport-options_2023-10-31-15-18.json
  docs/changehistory/NextVersion.md
  ui/appui-react/src/appui-react/content/IModelViewport.tsx
Labels: patch

#543 Add frontstage stories
  docs/storybook/src/AppUiStory.tsx
  docs/storybook/src/ReactContentControl.tsx
  docs/storybook/src/Utils.tsx
  docs/storybook/src/VirtualCursor.ts
  docs/storybook/src/frontstage/Frontstage.stories.tsx
  docs/storybook/src/frontstage/Frontstage.tsx
  docs/storybook/src/widget/CanFloat.tsx
  docs/storybook/src/widget/EmptyState.tsx
Labels: internal

#557 Resize Popout to fit content on popout
  common/changes/@itwin/appui-layout-react/joeh-resizePopout_2023-11-02-18-19.json
  common/changes/@itwin/appui-react/joeh-resizePopout_2023-11-02-18-19.json
  docs/changehistory/NextVersion.md
  full-stack-tests/ui/tests/popout-widget.test.ts
  full-stack-tests/ui/tests/popout-widget.test.ts-snapshots/popout-widget-should-apply-styles-to-popout-1-chromium-win32.png
  ui/appui-layout-react/src/appui-layout-react/state/NineZoneStateReducer.ts
  ui/appui-layout-react/src/appui-layout-react/widget/ContentRenderer.tsx
  ui/appui-layout-react/src/test/state/NineZoneStateReducer.test.ts
  ui/appui-react/src/appui-react/childwindow/PopoutWidget.tsx
Labels: patch

#577 Create `PreviewFeatures` system
  common/api/appui-layout-react.api.md
  common/api/appui-react.api.md
  common/api/summary/appui-layout-react.exports.csv
  common/api/summary/appui-react.exports.csv
  common/changes/@itwin/appui-layout-react/raplemie-previewFeatures_2023-11-03-12-52.json
  common/changes/@itwin/appui-react/raplemie-previewFeatures_2023-11-03-12-52.json
  docs/changehistory/NextVersion.md
  full-stack-tests/ui/tests/statusbar/status-bar.test.ts
  full-stack-tests/ui/tests/statusbar/status-bar.test.ts-snapshots/status-bar-test-1-chromium-win32.png
  full-stack-tests/ui/tests/statusbar/tile-loading-indicator.test.ts-snapshots/tile-loading-indicator-test-1-chromium-win32.png
  test-apps/appui-test-app/appui-test-providers/src/appui-test-providers.ts
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/PreviewFeaturesToggleProvider.tsx
  test-apps/appui-test-app/connected/src/frontend/index.tsx
  test-apps/appui-test-app/standalone/src/frontend/index.tsx
  ui/appui-layout-react/src/appui-layout-react.ts
  ui/appui-layout-react/src/appui-layout-react/preview/PreviewFeatures.tsx
  ui/appui-layout-react/src/appui-layout-react/tool-settings/Docked.scss
  ui/appui-layout-react/src/appui-layout-react/tool-settings/Docked.tsx
  ui/appui-layout-react/src/appui-layout-react/widget-panels/AppContent.tsx
  ui/appui-layout-react/src/test/preview/PreviewFeatures.test.tsx
  ui/appui-react/src/appui-react.ts
  ui/appui-react/src/appui-react/UiFramework.ts
  ui/appui-react/src/appui-react/configurableui/state.ts
  ui/appui-react/src/appui-react/preview/PreviewFeatures.ts
  ui/appui-react/src/appui-react/widget-panels/Frontstage.scss
  ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
  ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx
  ui/appui-react/src/test/UiFramework.test.ts
  ui/appui-react/src/test/redux/StateManager.test.ts
Labels: minor

#581 New `enableMaximizedFloatingWidget` preview feature
  common/api/appui-layout-react.api.md
  common/api/appui-react.api.md
  common/api/summary/appui-layout-react.exports.csv
  common/api/summary/appui-react.exports.csv
  common/changes/@itwin/appui-layout-react/raplemie-previewMaximizeFloating_2023-11-09-19-21.json
  common/changes/@itwin/appui-react/raplemie-previewMaximizeFloating_2023-11-09-19-21.json
  docs/changehistory/NextVersion.md
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/PreviewFeaturesToggleProvider.tsx
  ui/appui-layout-react/src/appui-layout-react/preview/PreviewFeatures.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/Buttons.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.scss
  ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/PreviewMaximizeToggle.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/Tab.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/TabBar.scss
  ui/appui-layout-react/src/test/preview/PreviewFeatures.test.tsx
  ui/appui-react/src/appui-react/configurableui/state.ts
  ui/appui-react/src/appui-react/preview/PreviewFeatures.ts
Labels: minor

#582 Hidden Widget does not ignore DefaultPosition and DefaultSize when set to floating
  common/changes/@itwin/appui-layout-react/joeh-defaultPositionWhenHidden_2023-11-09-20-20.json
  common/changes/@itwin/appui-react/joeh-defaultPositionWhenHidden_2023-11-09-20-20.json
  docs/changehistory/NextVersion.md
  ui/appui-layout-react/src/appui-layout-react/state/NineZoneStateReducer.ts
  ui/appui-react/src/appui-react/widgets/WidgetDef.tsx
Labels: patch

#583 Missing refresh of tool setting source on mount
  common/changes/@itwin/appui-react/raplemie-widgetToolSettingsRefresh_2023-11-10-21-44.json
  docs/changehistory/NextVersion.md
  full-stack-tests/ui/tests/tool-settings.test.ts
  test-apps/appui-test-app/appui-test-providers/src/tools/SampleTool.ts
  ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx
Labels: patch

#595 Fix setting save effect dependency
  common/changes/@itwin/appui-react/raplemie-fixSettingsSaveEffect_2023-11-20-18-09.json
  full-stack-tests/ui/tests/popout-widget.test.ts
  ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
Labels: patch

#596 Reorder #515 previous fix
  common/changes/@itwin/appui-react/raplemie-saveOrderIssue_2023-11-21-15-19.json
  ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
Labels: patch

#597 Add double-click support in TreeEvents
  common/api/components-react.api.md
  common/changes/@itwin/components-react/tree-events-add-double-click-support_2023-11-22-16-52.json
  docs/changehistory/NextVersion.md
  ui/components-react/src/components-react/tree/controlled/TreeEventDispatcher.ts
  ui/components-react/src/components-react/tree/controlled/TreeEventHandler.ts
  ui/components-react/src/components-react/tree/controlled/TreeEvents.ts
  ui/components-react/src/test/tree/controlled/TreeEventDispatcher.test.ts
  ui/components-react/src/test/tree/controlled/TreeEventHandler.test.ts
Labels: minor

#604 Update Preview Feature management.
  common/api/appui-layout-react.api.md
  common/api/appui-react.api.md
  common/api/summary/appui-layout-react.exports.csv
  common/api/summary/appui-react.exports.csv
  common/changes/@itwin/appui-layout-react/raplemie-simplifyPreviewLayoutFeatures_2023-11-24-21-56.json
  common/changes/@itwin/appui-react/raplemie-simplifyPreviewLayoutFeatures_2023-11-24-21-56.json
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/PreviewFeaturesToggleProvider.tsx
  test-apps/appui-test-app/connected/src/frontend/index.tsx
  test-apps/appui-test-app/standalone/src/frontend/index.tsx
  ui/appui-layout-react/src/appui-layout-react.ts
  ui/appui-layout-react/src/appui-layout-react/preview/PreviewFeatures.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/Buttons.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/FloatingWidget.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/PreviewMaximizeToggle.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/Tab.tsx
  ui/appui-layout-react/src/test/preview/PreviewFeatures.test.tsx
  ui/appui-react/src/appui-react.ts
  ui/appui-react/src/appui-react/UiFramework.ts
  ui/appui-react/src/appui-react/preview/PreviewFeatures.tsx
  ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
  ui/appui-react/src/test/UiFramework.test.ts
  ui/appui-react/src/test/preview/PreviewFeatures.test.tsx
  ui/appui-react/src/test/setup.test.ts
Labels: minor

#605 Fix incorrect multiline value renderer
  common/changes/@itwin/components-react/fix-record-value-renderers_2023-11-27-13-05.json
  docs/changehistory/NextVersion.md
  ui/components-react/src/components-react/properties/renderers/value/Common.ts
  ui/components-react/src/components-react/properties/renderers/value/DoublePropertyValueRenderer.tsx
  ui/components-react/src/components-react/properties/renderers/value/MultilineTextPropertyValueRenderer.tsx
  ui/components-react/src/components-react/properties/renderers/value/NavigationPropertyValueRenderer.tsx
  ui/components-react/src/test/TestUtils.ts
  ui/components-react/src/test/properties/renderers/MultilineTextPropertyValueRenderer.test.tsx
  ui/components-react/src/test/propertygrid/component/VirtualizedPropertyGridWithDataProvider.test.tsx
Labels: patch

#609 Remove unneeded UiFramework complexity
  common/api/appui-react.api.md
  common/changes/@itwin/appui-react/raplemie-unneededComplexity_2023-11-29-17-16.json
  ui/appui-react/src/appui-react/UiFramework.ts
Labels: internal
