Repository iTwin/appui, pull requests merged in 2023-10, with the labels that each got.

#508 Fix grips flickers + AUDIT FIX
  common/changes/@itwin/appui-layout-react/raplemie-gripTransitionIssue_2023-10-02-19-37.json
  common/changes/@itwin/appui-layout-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
  common/changes/@itwin/appui-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
  common/changes/@itwin/components-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
  common/changes/@itwin/core-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
  common/changes/@itwin/imodel-components-react/raplemie-gripTransitionIssue_2023-10-02-20-28.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/core-3x/pnpm-lock.yaml
  docs/changehistory/NextVersion.md
  ui/appui-layout-react/package.json
  ui/appui-layout-react/src/appui-layout-react/widget-panels/Grip.scss
  ui/appui-react/package.json
  ui/components-react/package.json
  ui/core-react/package.json
  ui/imodel-components-react/package.json
Labels: patch

#507 Revert iTwinUI dependency upgrade.
  common/changes/@itwin/appui-react/raplemie-revertITwinUIPackages_2023-10-02-16-45.json
  common/changes/@itwin/components-react/raplemie-revertITwinUIPackages_2023-10-02-16-45.json
  common/changes/@itwin/core-react/raplemie-revertITwinUIPackages_2023-10-02-16-45.json
  common/changes/@itwin/imodel-components-react/raplemie-revertITwinUIPackages_2023-10-02-16-45.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/core-3x/pnpm-lock.yaml
  docs/changehistory/NextVersion.md
  full-stack-tests/ui/tests/picker/view-selector.test.ts-snapshots/view-selector-test-1-chromium-win32.png
  full-stack-tests/ui/tests/popout-widget.test.ts
  full-stack-tests/ui/tests/popout-widget.test.ts-snapshots/popout-widget-should-apply-styles-to-popout-1-chromium-win32.png
  full-stack-tests/ui/tests/popup/keyin-palette-panel.test.ts-snapshots/keyin-palette-panel-test-1-chromium-win32.png
  test-apps/appui-test-app/appui-test-providers/package.json
  test-apps/appui-test-app/connected/package.json
  test-apps/appui-test-app/standalone/package.json
  ui/appui-react/package.json
  ui/appui-react/src/test/childwindow/ChildWindowManager.test.tsx
  ui/components-react/package.json
  ui/core-react/package.json
  ui/imodel-components-react/package.json
Labels: patch

#505 Widget No Longer Disappears When Popout Fails
  common/api/appui-react.api.md
  common/changes/@itwin/appui-layout-react/joeh-iframeTesting_2023-09-28-15-54.json
  common/changes/@itwin/appui-react/joeh-iframeTesting_2023-09-28-15-54.json
  docs/changehistory/NextVersion.md
  ui/appui-layout-react/src/appui-layout-react/state/internal/WidgetStateHelpers.ts
  ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
  ui/appui-react/src/test/TestUtils.ts
  ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
  ui/scripts/setup-tests.js
Labels: patch

#520 Notifications - #471 and #519
  common/api/appui-react.api.md
  common/changes/@itwin/appui-react/raplemie-cleanNotifications_2023-10-11-18-36.json
  common/changes/@itwin/appui-react/raplemie-cleanNotifications_2023-10-11-18-39.json
  docs/changehistory/NextVersion.md
  full-stack-tests/ui/tests/notification/message-center-field.test.ts
  full-stack-tests/ui/tests/notification/message-center-field.test.ts-snapshots/message-center-field-HTML-and-React-message-and-overflow-test-1-chromium-win32.png
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/ComponentExamplesProvider.tsx
  ui/appui-react/package.json
  ui/appui-react/src/appui-react/configurableui/ConfigurableUiContent.tsx
  ui/appui-react/src/appui-react/messages/MessageManager.tsx
  ui/appui-react/src/appui-react/statusbar/StatusBar.tsx
  ui/appui-react/src/appui-react/statusfields/MessageCenter.tsx
  ui/appui-react/src/test/messages/ActivityMessage.test.tsx
  ui/appui-react/src/test/messages/MessageManager.test.tsx
  ui/appui-react/src/test/statusbar/StatusBar.test.tsx
  ui/appui-react/src/test/statusfields/MessageCenter.test.tsx
Labels: minor

#534 Support non base64 data:image/svg+xml icons.
  common/changes/@itwin/core-react/raplemie-nonBase64dataIcon_2023-10-13-18-12.json
  ui/core-react/src/core-react/utils/IconWebComponent.ts
  ui/core-react/src/test/icons/IconComponent.test.tsx
Labels: patch

#517 Unmount InternalChildWindowManager whenever Window is closed
  common/changes/@itwin/appui-react/joeh-ghostWidget_2023-10-09-13-52.json
  docs/changehistory/NextVersion.md
  full-stack-tests/ui/tests/popout-widget.test.ts
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/FloatingWidgetsUiItemsProvider.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/widgets/PopoutMountUnmountWidget.tsx
  ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
  ui/appui-react/src/appui-react/popup/PopupManager.tsx
  ui/appui-react/src/test/popup/PopupManager.test.tsx
Labels: patch

#541 4.6.2 changelogs
  common/changes/@itwin/appui-layout-react/changelogs-4.6.2_2023-10-17-20-16.json
  common/changes/@itwin/appui-react/changelogs-4.6.2_2023-10-17-20-16.json
  common/changes/@itwin/appui-react/joeh-ghostWidget_2023-10-09-13-52.json
  common/changes/@itwin/components-react/changelogs-4.6.2_2023-10-17-20-16.json
  common/changes/@itwin/core-react/changelogs-4.6.2_2023-10-17-20-16.json
  common/changes/@itwin/core-react/raplemie-nonBase64dataIcon_2023-10-13-18-12.json
  common/changes/@itwin/imodel-components-react/changelogs-4.6.2_2023-10-17-20-16.json
  ui/appui-layout-react/CHANGELOG.json
  ui/appui-layout-react/CHANGELOG.md
  ui/appui-react/CHANGELOG.json
  ui/appui-react/CHANGELOG.md
  ui/components-react/CHANGELOG.json
  ui/components-react/CHANGELOG.md
  ui/core-react/CHANGELOG.json
  ui/core-react/CHANGELOG.md
  ui/imodel-components-react/CHANGELOG.json
  ui/imodel-components-react/CHANGELOG.md
Labels: internal

#546 Fix custom hooks not working in React 18 strict mode
  common/changes/@itwin/components-react/hooks_fix_2023-10-20-12-48.json
  common/changes/@itwin/core-react/hooks_fix_2023-10-20-12-48.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/core-3x/pnpm-lock.yaml
  docs/changehistory/NextVersion.md
  ui/components-react/package.json
  ui/components-react/src/components-react/common/UseAsyncValue.tsx
  ui/components-react/src/components-react/common/UseDebouncedAsyncValue.ts
  ui/components-react/src/test/common/UseDebouncedAsyncValue.test.tsx
  ui/core-react/src/core-react/utils/hooks/useDisposable.ts
Labels: patch

#547 Add iTwinUI high contrast theme support
  common/api/appui-react.api.md
  common/api/summary/appui-react.exports.csv
  common/changes/@itwin/appui-react/raplemie-ThemeManager_2023-10-20-20-14.json
  common/changes/@itwin/appui-react/raplemie-ThemeManager_2023-10-20-20-15.json
  common/changes/@itwin/core-react/raplemie-ThemeManager_2023-10-20-20-14.json
  common/changes/@itwin/core-react/raplemie-ThemeManager_2023-10-20-20-15.json
  full-stack-tests/ui/tests/settings/ui-settings-page.test.ts-snapshots/ui-settings-page-test-1-chromium-win32.png
  ui/appui-react/public/locales/en/UiFramework.json
  ui/appui-react/src/appui-react/UiFramework.ts
  ui/appui-react/src/appui-react/configurableui/state.ts
  ui/appui-react/src/appui-react/navigationaids/SheetNavigationAid.scss
  ui/appui-react/src/appui-react/navigationaids/SheetNavigationAid.tsx
  ui/appui-react/src/appui-react/settings/ui/UiSettingsPage.tsx
  ui/appui-react/src/appui-react/theme/ThemeManager.tsx
  ui/appui-react/src/appui-react/uistate/AppUiSettings.ts
  ui/appui-react/src/test/settings/UiSettingsPage.test.tsx
  ui/core-react/src/core-react/colorthemes.scss
  ui/core-react/src/core-react/colorvariables.scss
  ui/core-react/src/core-react/uistate/UiStateEntry.ts
Labels: minor

#504 Update `UiItemsProvider` to facilitate overriding
  common/api/appui-react.api.md
  common/api/summary/appui-react.exports.csv
  common/changes/@itwin/appui-react/items-provider_2023-10-06-10-54.json
  docs/changehistory/NextVersion.md
  docs/storybook/src/hooks/useIsBackstageOpen.stories.tsx
  full-stack-tests/ui/tests/Utils.ts
  full-stack-tests/ui/tests/ui-items-provider.test.ts
  test-apps/appui-test-app/appui-test-providers/src/ui/frontstages/WidgetApiStage.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/UpdatedUiItemsProvider.tsx
  ui/appui-react/src/appui-react/toolbar/ToolbarItem.ts
  ui/appui-react/src/appui-react/ui-items-provider/AbstractUiItemsManager.ts
  ui/appui-react/src/appui-react/ui-items-provider/UiItemsManager.ts
  ui/appui-react/src/appui-react/ui-items-provider/UiItemsProvider.ts
  ui/appui-react/src/appui-react/widgets/Widget.tsx
  ui/appui-react/src/test/ui-items-provider/UiItemsManager.test.tsx
Labels: minor

#567 Update readme
  README.md
  full-stack-tests/ui/README.md
Labels: internal

#572 Remove remaining UI 2.0 mentions in docs.
  common/changes/@itwin/appui-layout-react/raplemie-v2JsDocCleanup_2023-10-30-21-01.json
  common/changes/@itwin/appui-react/raplemie-v2JsDocCleanup_2023-10-30-21-01.json
  full-stack-tests/ui/tests/settings/ui-settings-page.test.ts-snapshots/ui-settings-page-test-1-chromium-win32.png
  test-apps/appui-test-app/connected/src/frontend/index.tsx
  ui/appui-layout-react/src/appui-layout-react/widget/_variables.scss
  ui/appui-react/public/locales/en/UiFramework.json
  ui/appui-react/src/appui-react/UiFramework.ts
  ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
  ui/appui-react/src/appui-react/settings/ui/UiSettingsPage.tsx
  ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx
  ui/appui-react/src/test/toolbar/ToolbarComposer.test.tsx
  ui/appui-react/src/test/widgets/ToolWidgetComposer.test.tsx
Labels: patch
