Repository iTwin/appui, pull requests merged in 2023-12, with the labels that each got.

#610 Fix timeline duration props update issue.
  common/changes/@itwin/imodel-components-react/raplemie-timelineTimingIssue_2023-11-30-20-42.json
  full-stack-tests/ui/tests/timeline/timeline.test.ts
  full-stack-tests/ui/tests/timeline/timeline.test.ts-snapshots/timeline-handle-simultaneous-initial-and-total-duration-props-change-regression-test-1-chromium-win32.png
  full-stack-tests/ui/tests/timeline/timeline.test.ts-snapshots/timeline-handle-simultaneous-initial-and-total-duration-props-change-regression-test-2-chromium-win32.png
  full-stack-tests/ui/tests/timeline/timeline.test.ts-snapshots/timeline-handle-simultaneous-initial-and-total-duration-props-change-regression-test-3-chromium-win32.png
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/ComponentExamplesProvider.tsx
  ui/imodel-components-react/src/imodel-components-react/timeline/TimelineComponent.tsx
Labels: patch

#606 Retain widget changes when popped out and sent back
  common/changes/@itwin/appui-layout-react/joeh-popoutStateChange_2023-12-01-17-10.json
  common/changes/@itwin/appui-react/joeh-popoutStateChange_2023-11-27-17-47.json
  docs/changehistory/NextVersion.md
  full-stack-tests/ui/tests/popout-widget.test.ts
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/ContentLayoutStageUiItemsProvider.tsx
  ui/appui-react/src/appui-react/childwindow/InternalChildWindowManager.tsx
  ui/appui-react/src/appui-react/childwindow/PopoutWidget.tsx
  ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
  ui/appui-react/src/test/childwindow/PopoutWidget.test.snap
  ui/appui-react/src/test/childwindow/PopoutWidget.test.tsx
Labels: minor

#616 Delay viewport creation to non 0x0 div.
  common/changes/@itwin/appui-react/raplemie-0x0ViewportHandling_2023-12-04-21-46.json
  common/changes/@itwin/imodel-components-react/raplemie-0x0ViewportHandling_2023-12-04-21-46.json
  ui/appui-react/src/appui-react/content/InternalContentViewManager.ts
  ui/imodel-components-react/src/imodel-components-react/viewport/ViewportComponent.tsx
  ui/imodel-components-react/src/test/viewport/ViewportComponent.test.tsx
Labels: patch

#618 Promote `FrameworkToolAdmin` to _beta_
  common/api/appui-react.api.md
  common/api/summary/appui-react.exports.csv
  common/changes/@itwin/appui-react/raplemie-frameworkToolAdminBeta_2023-12-05-21-16.json
  docs/changehistory/NextVersion.md
  ui/appui-react/src/appui-react/tools/FrameworkToolAdmin.ts
Labels: patch

#619 Change behavior of property setting in Filter State
  common/changes/@itwin/components-react/filter-builder-default-operator_2023-12-06-09-47.json
  docs/changehistory/NextVersion.md
  ui/components-react/src/components-react/filter-builder/FilterBuilderState.ts
  ui/components-react/src/test/filter-builder/FilterBuilderState.test.ts
Labels: patch

#620 Fix constructors of data filterers
  common/changes/@itwin/components-react/filterer-edit-filtering-constructors_2023-12-07-13-35.json
  docs/changehistory/NextVersion.md
  ui/components-react/src/components-react/propertygrid/dataproviders/filterers/DisplayValuePropertyDataFilterer.ts
  ui/components-react/src/components-react/propertygrid/dataproviders/filterers/LabelPropertyDataFilterer.ts
  ui/components-react/src/components-react/propertygrid/dataproviders/filterers/PropertyCategoryLabelFilterer.ts
  ui/components-react/src/test/propertygrid/dataproviders/filterers/DisplayValuePropertyDataFilterer.test.ts
  ui/components-react/src/test/propertygrid/dataproviders/filterers/LabelPropertyDataFilterer.test.ts
  ui/components-react/src/test/propertygrid/dataproviders/filterers/PropertyCategoryLabelFilterer.test.ts
Labels: patch

#617 Keep widget content unmounted while widget state is set to `WidgetState.Unloaded`
  common/api/appui-layout-react.api.md
  common/api/summary/appui-layout-react.exports.csv
  common/changes/@itwin/appui-layout-react/issue-338_2023-12-05-17-54.json
  common/changes/@itwin/appui-react/issue-338_2023-12-05-17-54.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/core-3x/pnpm-lock.yaml
  docs/changehistory/NextVersion.md
  docs/storybook/package.json
  docs/storybook/src/widget/Widget.stories.tsx
  docs/storybook/src/widget/Widget.tsx
  full-stack-tests/ui/tests/Utils.ts
  full-stack-tests/ui/tests/popout-widget.test.ts
  full-stack-tests/ui/tests/widget-state.test.ts
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/FloatingWidgetsUiItemsProvider.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/WidgetApiStageUiItemsProvider.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/widgets/LogLifecycleWidget.tsx
  ui/appui-layout-react/package.json
  ui/appui-layout-react/src/appui-layout-react/state/NineZoneAction.ts
  ui/appui-layout-react/src/appui-layout-react/state/NineZoneStateReducer.ts
  ui/appui-layout-react/src/appui-layout-react/state/TabState.ts
  ui/appui-layout-react/src/appui-layout-react/state/internal/TabStateHelpers.ts
  ui/appui-layout-react/src/appui-layout-react/state/internal/WidgetStateHelpers.ts
  ui/appui-layout-react/src/appui-layout-react/widget/ContentRenderer.tsx
  ui/appui-layout-react/src/test/state/NineZoneStateReducer.test.ts
  ui/appui-layout-react/src/test/state/internal/TabStateHelpers.test.ts
  ui/appui-layout-react/src/test/widget/ContentRenderer.test.tsx
  ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
  ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
  ui/appui-react/src/appui-react/widgets/Widget.tsx
  ui/appui-react/src/appui-react/widgets/WidgetDef.tsx
  ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
Labels: minor

#626 Backport 4.7.1 changelogs
  common/changes/@itwin/appui-layout-react/changelogs-4.7.1_2023-12-07-19-52.json
  common/changes/@itwin/appui-react/changelogs-4.7.1_2023-12-07-19-52.json
  common/changes/@itwin/appui-react/raplemie-0x0ViewportHandling_2023-12-04-21-46.json
  common/changes/@itwin/components-react/changelogs-4.7.1_2023-12-07-19-52.json
  common/changes/@itwin/components-react/filter-builder-default-operator_2023-12-06-09-47.json
  common/changes/@itwin/components-react/filterer-edit-filtering-constructors_2023-12-07-13-35.json
  common/changes/@itwin/core-react/changelogs-4.7.1_2023-12-07-19-52.json
  common/changes/@itwin/imodel-components-react/changelogs-4.7.1_2023-12-07-19-52.json
  common/changes/@itwin/imodel-components-react/raplemie-0x0ViewportHandling_2023-12-04-21-46.json
  ui/appui-layout-react/CHANGELOG.json
  ui/appui-layout-react/CHANGELOG.md
  ui/appui-react/CHANGELOG.json
  ui/appui-react/CHANGELOG.md
  ui/components-react/CHANGELOG.json
  ui/components-react/CHANGELOG.md
  ui/core-react/CHANGELOG.json
  ui/core-react/CHANGELOG.md
  ui/imodel-components-react/CHANGELOG.json
  ui/imodel-components-react/CHANGELOG.md
Labels: internal

#633 Fix RestoreLayout tool
  common/changes/@itwin/appui-react/raplemie-restoreLayout_2023-12-12-20-31.json
  docs/changehistory/NextVersion.md
  ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
  ui/appui-react/src/appui-react/preview/PreviewFeatures.tsx
  ui/appui-react/src/appui-react/widgets/WidgetDef.tsx
Labels: patch

#634 Augment README with HTML coverage report location.
  README.md
Labels: internal

#637 Fix logic of default orientation of PropertyGrid elements.
  common/changes/@itwin/components-react/property-grid-fix-default-orientation_2023-12-18-10-51.json
  docs/changehistory/NextVersion.md
  ui/components-react/src/components-react/propertygrid/component/VirtualizedPropertyGrid.tsx
  ui/components-react/src/test/propertygrid/component/VirtualizedPropertyGridWithDataProvider.test.tsx
Labels: patch
