Repository iTwin/appui, pull requests merged in 2024-01, with the labels that each got.

#661 Adding Testing options info to README (test-apps/storybook)
  README.md
  test-apps/appui-test-app/connected/README.md
  test-apps/appui-test-app/standalone/README.md
Labels: internal

#664 Add visual tests and story for Editors
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/core-3x/pnpm-lock.yaml
  docs/storybook/package.json
  docs/storybook/src/AppUiStory.tsx
  docs/storybook/src/components/Editors.stories.tsx
  full-stack-tests/ui/tests/configurableui/configurable-ui.test.ts
  full-stack-tests/ui/tests/configurableui/configurable-ui.test.ts-snapshots/configurable-ui-test-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-boolean-Default-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-boolean-image-check-box-UiAbstract-CheckBoxImages-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-boolean-toggle-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-dateTime-Default-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-enum-Default-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-enum-enum-buttongroup-UiAbstract-ButtonGroupData-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-enum-enum-buttongroup-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-number-number-custom-UiAbstra-caae8-mattedNumber-UiAbstract-Icon-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-number-number-custom-UiAbstract-CustomFormattedNumber-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-number-numeric-input-UiAbstract-InputEditorSize-UiAbstract-Range-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-number-numeric-input-UiAbstract-InputEditorSize-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-number-numeric-input-UiAbstract-Range-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-number-numeric-input-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-number-slider-UiAbstract-Slider-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-shortdate-Default-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-string-Default-default-visual-1-chromium-win32.png
  full-stack-tests/ui/tests/editors/editors.test.ts-snapshots/Editor-Primitive-string-multi-line-UiAbstract-MultilineText-default-visual-1-chromium-win32.png
  test-apps/appui-test-app/appui-test-providers/package.json
  test-apps/appui-test-app/appui-test-providers/src/ui/components/EditorExampleComponent.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/ComponentExamplesProvider.tsx
Labels: internal

#615 Add code snippets for the documentation
  common/changes/@itwin/components-react/docs-snippets_2024-01-22-09-04.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/variants/core-3x/pnpm-lock.yaml
  docs/storybook/package.json
  docs/storybook/src/AppUiStory.tsx
  docs/storybook/src/Utils.tsx
  docs/storybook/src/createContentControl.tsx
  docs/storybook/src/frontstage/Frontstage.stories.tsx
  docs/storybook/src/frontstage/ToolSettings.stories.tsx
  docs/storybook/src/frontstage/ToolSettings.tsx
  docs/storybook/src/tools/ToolSettingsProperties.tsx
  full-stack-tests/ui/tests/backstage/backstage.test.ts
  full-stack-tests/ui/tests/backstage/backstage.test.ts-snapshots/backstage-test-1-chromium-win32.png
  full-stack-tests/ui/tests/backstage/backstage.test.ts-snapshots/backstage-test-with-snapshotPath-1-chromium-win32.png
  full-stack-tests/ui/tests/backstage/backstage.test.ts-snapshots/backstage-test-without-snapshotPath-1-chromium-win32.png
  test-apps/appui-test-app/appui-test-providers/package.json
  test-apps/appui-test-app/appui-test-providers/src/appui-test-providers.ts
  test-apps/appui-test-app/appui-test-providers/src/docs/Backstage.SetUp.tsx
  test-apps/appui-test-app/appui-test-providers/src/docs/Frontstage.Activate.ts
  test-apps/appui-test-app/appui-test-providers/src/docs/UiItemsProvider.BackstageItems.ts
  test-apps/appui-test-app/appui-test-providers/src/docs/UiItemsProvider.Conditionals.tsx
  test-apps/appui-test-app/appui-test-providers/src/docs/UiItemsProvider.Override.ts
  test-apps/appui-test-app/appui-test-providers/src/docs/UiItemsProvider.Provider.ts
  test-apps/appui-test-app/appui-test-providers/src/docs/UiItemsProvider.Register.ts
  test-apps/appui-test-app/appui-test-providers/src/docs/UiItemsProvider.StatusBarItems.tsx
  test-apps/appui-test-app/appui-test-providers/src/docs/UiItemsProvider.ToolbarItems.tsx
  test-apps/appui-test-app/appui-test-providers/src/docs/UiItemsProvider.Widgets.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/content/ReactContentControl.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/frontstages/CustomFrontstageProvider.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/frontstages/registerCustomFrontstage.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/frontstages/registerStandardFrontstage.tsx
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/CustomStageUiItemsProvider.tsx
  test-apps/appui-test-app/standalone/src/frontend/appui/frontstages/example-stages/CustomFrontstage.tsx
  test-apps/appui-test-app/standalone/src/frontend/appui/frontstages/example-stages/ExampleStagesBackstageProvider.tsx
  test-apps/appui-test-app/standalone/src/frontend/index.tsx
  ui/components-react/src/test/propertygrid/component/ColumnResizingPropertyListPropsSupplier.test.tsx
Labels: documentation

#601 Add a preview feature not to close open widget after docking (drag&drop) into Panel
  common/api/appui-layout-react.api.md
  common/api/summary/appui-layout-react.exports.csv
  common/changes/@itwin/appui-layout-react/change_activeTab_in_preview_2023-11-24-13-38.json
  common/changes/@itwin/appui-react/change_activeTab_in_preview_2023-11-24-13-38.json
  docs/changehistory/NextVersion.md
  test-apps/appui-test-app/appui-test-providers/src/ui/providers/PreviewFeaturesToggleProvider.tsx
  ui/appui-layout-react/src/appui-layout-react.ts
  ui/appui-layout-react/src/appui-layout-react/preview/PreviewFeatures.tsx
  ui/appui-layout-react/src/appui-layout-react/state/activateDroppedTab.ts
  ui/appui-layout-react/src/test/state/activateDroppedTab.test.ts
  ui/appui-react/src/appui-react/preview/PreviewFeatures.tsx
  ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
Labels: minor

#682 Optionally do not clear selection on HideIsolateEmphasizeActionHandler.processIsolateSelected
  common/api/appui-react.api.md
  common/changes/@itwin/appui-react/dont-clear-selection-after-isolate_2024-01-19-10-45.json
  docs/changehistory/NextVersion.md
  ui/appui-react/src/appui-react/selection/HideIsolateEmphasizeManager.ts
Labels: minor
