Repository iTwin/appui, pull requests merged in 2024-05, with the labels that each got.

#831 `PropertyGrid`: render display value when available
  common/api/components-react.api.md
  common/api/summary/components-react.exports.csv
  common/changes/@itwin/components-react/value_renderers_2024-05-07-10-28.json
  ui/components-react/src/components-react/properties/ValueRendererManager.tsx
  ui/components-react/src/components-react/properties/renderers/value/PrimitivePropertyValueRenderer.tsx
  ui/components-react/src/components-react/properties/renderers/value/UrlPropertyValueRenderer.tsx
  ui/components-react/src/test/TestUtils.ts
  ui/components-react/src/test/properties/renderers/value/PrimitivePropertyValueRenderer.test.tsx
Labels: patch

#832 Deprecate unused property value renderers
  common/api/components-react.api.md
  common/api/summary/components-react.exports.csv
  common/changes/@itwin/components-react/deprecate_renderers_2024-05-07-11-19.json
  common/config/rush/pnpm-lock.yaml
  docs/changehistory/NextVersion.md
  ui/components-react/package.json
  ui/components-react/src/components-react/properties/renderers/value/DoublePropertyValueRenderer.tsx
  ui/components-react/src/components-react/properties/renderers/value/NavigationPropertyValueRenderer.tsx
  ui/components-react/src/components-react/propertygrid/internal/flat-items/MutableFlatGridItem.ts
  ui/components-react/src/test/properties/renderers/value/DoublePropertyValueRenderer.test.tsx
  ui/components-react/src/test/properties/renderers/value/NavigationPropertyValueRenderer.test.tsx
  ui/components-react/src/test/propertygrid/component/internal/flat-items/FlatGridTestUtils.ts
Labels: minor, dependencies

#850 Deprecate `RadialMenu` and `RadialButton` components
  common/api/core-react.api.md
  common/api/summary/core-react.exports.csv
  common/changes/@itwin/core-react/deprecate-radial-menu_2024-05-23-07-38.json
  docs/changehistory/NextVersion.md
  docs/storybook/src/deprecated/RadialMenu.stories.tsx
  ui/core-react/eslint.config.js
  ui/core-react/src/core-react/radialmenu/RadialMenu.tsx
  ui/core-react/src/test/UiCore.test.ts
  ui/core-react/src/test/base/Centered.test.tsx
  ui/core-react/src/test/base/DivWithOutsideClick.test.tsx
  ui/core-react/src/test/base/FillCentered.test.tsx
  ui/core-react/src/test/base/FlexWrapContainer.test.tsx
  ui/core-react/src/test/base/Gap.test.tsx
  ui/core-react/src/test/base/ScrollView.test.tsx
  ui/core-react/src/test/button/UnderlinedButton.test.tsx
  ui/core-react/src/test/checklistbox/CheckListBox.test.tsx
  ui/core-react/src/test/dialog/Dialog.test.tsx
  ui/core-react/src/test/elementseparator/ElementSeparator.test.tsx
  ui/core-react/src/test/expandable/ExpandableList.test.tsx
  ui/core-react/src/test/imagecheckbox/ImageCheckBox.test.tsx
  ui/core-react/src/test/inputs/InputLabel.test.tsx
  ui/core-react/src/test/inputs/iconinput/IconInput.test.tsx
  ui/core-react/src/test/inputs/numberinput/NumberInput.test.tsx
  ui/core-react/src/test/listbox/listbox.test.tsx
  ui/core-react/src/test/loading/LoadingBar.test.tsx
  ui/core-react/src/test/loading/LoadingPrompt.test.tsx
  ui/core-react/src/test/loading/LoadingSpinner.test.tsx
  ui/core-react/src/test/loading/LoadingStatus.test.tsx
  ui/core-react/src/test/notification/MessageRenderer.test.tsx
  ui/core-react/src/test/searchbox/SearchBox.test.tsx
  ui/core-react/src/test/tabs/Tabs.test.tsx
  ui/core-react/src/test/tabs/VerticalTabs.test.tsx
  ui/core-react/src/test/text/BlockText.test.tsx
  ui/core-react/src/test/text/BodyText.test.tsx
  ui/core-react/src/test/text/DisabledText.test.tsx
  ui/core-react/src/test/text/MutedText.test.tsx
  ui/core-react/src/test/utils/hooks/useDisposable.test.tsx
Labels: minor

#849 Fix property grid text selection
  common/changes/@itwin/components-react/jon-fix-property-grid-text-selection_2024-05-23-06-54.json
  common/changes/@itwin/core-react/jon-fix-property-grid-text-selection_2024-05-23-06-54.json
  docs/changehistory/NextVersion.md
  docs/storybook/src/components/PropertyGrid.stories.tsx
  ui/components-react/src/components-react/properties/renderers/PropertyGridColumns.ts
  ui/components-react/src/components-react/properties/renderers/PropertyView.tsx
  ui/components-react/src/components-react/properties/renderers/label/PropertyLabelRenderer.scss
  ui/components-react/src/components-react/properties/renderers/label/PropertyLabelRenderer.tsx
  ui/components-react/src/components-react/propertygrid/component/PropertyGridEventsRelatedPropsSupplier.tsx
  ui/components-react/src/components-react/propertygrid/component/VirtualizedPropertyGrid.scss
  ui/components-react/src/test/properties/renderers/PropertyView.test.tsx
  ui/components-react/src/test/propertygrid/component/ColumnResizingPropertyListPropsSupplier.test.tsx
  ui/core-react/src/core-react/elementseparator/ElementSeparator.scss
  ui/core-react/src/core-react/elementseparator/ElementSeparator.tsx
Labels: minor
