Repository iTwin/appui, pull requests merged in 2025-02, with the labels that each got.

#1210 Add `useSavedState` flag to `Widget` config
  apps/test-app/src/frontend/appui/frontstages/TestWidgetFrontstage.tsx
  apps/test-app/src/frontend/appui/frontstages/createTestFrontstage.tsx
  apps/test-app/src/frontend/registerFrontstages.tsx
  common/api/appui-react.api.md
  common/changes/@itwin/appui-react/widget-useSavedState_2025-02-06-13-41.json
  docs/changehistory/NextVersion.md
  e2e-tests/tests/widget-state.test.ts
  ui/appui-react/src/appui-react/widget-panels/Frontstage.tsx
  ui/appui-react/src/appui-react/widgets/Widget.tsx
Labels: minor

#1221 Update `vitest` version
  common/changes/@itwin/appui-react/bump-vitest_2025-02-19-08-34.json
  common/changes/@itwin/components-react/bump-vitest_2025-02-19-08-34.json
  common/changes/@itwin/core-react/bump-vitest_2025-02-19-08-34.json
  common/changes/@itwin/imodel-components-react/bump-vitest_2025-02-19-08-34.json
  common/config/rush/pnpm-lock.yaml
  ui/appui-react/package.json
  ui/appui-react/src/appui-react/UiFramework.ts
  ui/appui-react/src/test/UiFramework.test.ts
  ui/appui-react/src/test/frontstage/FrontstageDef.test.tsx
  ui/appui-react/src/test/layout/base/NineZone.test.tsx
  ui/appui-react/src/test/layout/tool-settings/Handle.test.tsx
  ui/appui-react/src/test/layout/widget-panels/Expander.test.tsx
  ui/appui-react/src/test/layout/widget-panels/Grip.test.tsx
  ui/appui-react/src/test/layout/widget-panels/Panel.test.tsx
  ui/appui-react/src/test/layout/widget-panels/usePanelsAutoCollapse.test.tsx
  ui/appui-react/src/test/layout/widget/Dock.test.tsx
  ui/appui-react/src/test/layout/widget/FloatingTab.test.tsx
  ui/appui-react/src/test/layout/widget/FloatingWidget.test.tsx
  ui/appui-react/src/test/layout/widget/PanelWidget.test.tsx
  ui/appui-react/src/test/layout/widget/PinToggle.test.tsx
  ui/appui-react/src/test/layout/widget/PopoutToggle.test.tsx
  ui/appui-react/src/test/layout/widget/SendBack.test.tsx
  ui/appui-react/src/test/layout/widget/Tab.test.tsx
  ui/appui-react/src/test/layout/widget/TabBar.test.tsx
  ui/appui-react/src/test/layout/widget/Widget.test.tsx
  ui/appui-react/src/test/statusfields/SnapMode.test.tsx
  ui/appui-react/vitest.config.ts
  ui/components-react/package.json
  ui/components-react/src/test/tree/controlled/TreeEventDispatcher.test.ts
  ui/components-react/src/test/tree/controlled/internal/TreeModelMutator.test.ts
  ui/components-react/vitest.config.ts
  ui/core-react/package.json
  ui/core-react/src/test/elementseparator/ElementSeparator.test.tsx
  ui/core-react/src/test/tree/Tree.test.tsx
  ui/core-react/src/test/utils/hooks/useDisposable.test.tsx
  ui/core-react/src/test/utils/hooks/useOnOutsideClick.test.tsx
  ui/core-react/src/test/utils/hooks/useRefEffect.test.tsx
  ui/core-react/vitest.config.ts
  ui/imodel-components-react/package.json
  ui/imodel-components-react/src/test/TestUtils.ts
  ui/imodel-components-react/src/test/quantityformat/FormatUnits.test.tsx
  ui/imodel-components-react/vitest.config.ts
Labels: internal

#1214 Adding -g option to rimraf and updating node version
  .github/workflows/CI.yaml
  .github/workflows/extract-api.yaml
  .github/workflows/publish-storybook.yaml
  README.md
  apps/test-app/package.json
  apps/test-providers/package.json
  common/changes/@itwin/appui-react/Linas-updating-rimraf-arguments-and-deps_2025-02-14-09-12.json
  common/changes/@itwin/components-react/Linas-updating-rimraf-arguments-and-deps_2025-02-14-09-12.json
  common/changes/@itwin/core-react/Linas-updating-rimraf-arguments-and-deps_2025-02-14-09-12.json
  common/changes/@itwin/imodel-components-react/Linas-updating-rimraf-arguments-and-deps_2025-02-14-09-12.json
  common/config/azure-pipelines/jobs/docs-ci.yaml
  rush.json
  ui/appui-react/package.json
  ui/components-react/package.json
  ui/core-react/package.json
  ui/imodel-components-react/package.json
Labels: internal

#1213 Enable iTwinUI v5 theme bridge
  apps/test-app/README.md
  apps/test-app/package.json
  apps/test-app/src/routes/__root.tsx
  apps/test-app/src/routes/iTwin_.$iTwinId.tsx
  apps/test-app/src/routes/iTwins.tsx
  apps/test-app/src/routes/local.lazy.tsx
  apps/test-providers/package.json
  common/changes/@itwin/appui-react/theme-bridge_2025-02-20-08-14.json
  common/changes/@itwin/components-react/theme-bridge_2025-02-20-08-14.json
  common/changes/@itwin/core-react/theme-bridge_2025-02-20-08-14.json
  common/changes/@itwin/imodel-components-react/theme-bridge_2025-02-20-08-14.json
  common/config/rush/pnpm-lock.yaml
  docs/storybook/.storybook/addons/ThemeBridge.tsx
  docs/storybook/.storybook/preview.ts
  docs/storybook/package.json
  ui/appui-react/package.json
  ui/appui-react/src/appui-react/theme/ThemeManager.tsx
  ui/appui-react/src/test/messages/MessageManager.test.tsx
  ui/appui-react/src/test/messages/MessageRenderer.test.tsx
  ui/components-react/package.json
  ui/core-react/package.json
  ui/imodel-components-react/package.json
Labels: documentation, internal
