Repository iTwin/appui, pull requests merged in 2025-01, with the labels that each got.

#1137 Added possibility to customize node if tool settings have no entries
  common/api/appui-react.api.md
  common/changes/@itwin/appui-react/MBudrevicius-CustomMessageV1_2024-12-11-11-22.json
  docs/changehistory/NextVersion.md
  ui/appui-react/src/appui-react/frontstage/FrontstageConfig.ts
  ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
  ui/appui-react/src/appui-react/widget-panels/ToolSettings.tsx
  ui/appui-react/src/test/widget-panels/ToolSettings.test.tsx
Labels: minor

#1157 Accudraw update fixes
  apps/test-app/src/routes/briefcase.lazy.tsx
  common/api/appui-react.api.md
  common/changes/@itwin/appui-react/accudraw_update_fixes_2024-12-13-20-55.json
  docs/changehistory/NextVersion.md
  e2e-tests/tests/accudraw/accudraw-dialog.test.ts-snapshots/accudraw-dialog-test-1-chromium-linux.png
  e2e-tests/tests/configurableui/configurable-ui.test.ts-snapshots/configurable-ui-test-1-chromium-linux.png
  ui/appui-react/src/appui-react/accudraw/AccuDrawFieldContainer.tsx
  ui/appui-react/src/appui-react/accudraw/AccuDrawInputField.scss
  ui/appui-react/src/appui-react/accudraw/AccuDrawInputField.tsx
  ui/appui-react/src/appui-react/accudraw/FrameworkAccuDraw.ts
  ui/appui-react/src/appui-react/preview/PreviewFeatures.tsx
  ui/appui-react/src/appui-react/preview/allow-bearing-letters-in-accudraw-input-fields/useAllowBearingLettersInAccuDrawInputFields.tsx
  ui/appui-react/src/appui-react/preview/enable-colorless-accudraw-input-fields/useEnableColorlessAccuDrawInputFields.tsx
  ui/appui-react/src/test/accudraw/AccuDrawFieldContainer.test.tsx
  ui/appui-react/src/test/accudraw/AccuDrawInputField.test.tsx
Labels: minor

#1171 Fix `useWidget` hook issue when used in a popout widget
  common/changes/@itwin/appui-react/issue-1170_2025-01-15-09-45.json
  e2e-tests/tests/popout-widget.test.ts
  ui/appui-react/src/appui-react/frontstage/FrontstageDef.tsx
Labels: bug, patch

#1174 Use import attributes when importing json files
  .prettierignore
  common/changes/@itwin/appui-react/issue-1165_2025-01-15-15-07.json
  common/changes/@itwin/components-react/issue-1165_2025-01-15-15-07.json
  common/changes/@itwin/core-react/issue-1165_2025-01-15-15-07.json
  common/changes/@itwin/imodel-components-react/issue-1165_2025-01-15-15-07.json
  ui/appui-react/src/appui-react/hooks/useTranslation.tsx
  ui/components-react/src/components-react/l10n/useTranslation.tsx
  ui/core-react/src/core-react/l10n/useTranslation.tsx
  ui/imodel-components-react/src/imodel-components-react/useTranslation.tsx
Labels: patch

#1193 Remove @itwin/core-telemetry from @itwin/appui-react peerDependencies
  common/changes/@itwin/appui-react/JonasD-telemetry-peerDep-removal_2025-01-29-11-38.json
  ui/appui-react/package.json
Labels: minor
